wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.36.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1707127942
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 13
      4: 3.9.12
      5: 0.12.21
      6: 4.36.0
      8:
      - 5
agnostic:
  desc: null
  value: false
algorithm:
  desc: null
  value: ga
api_idx:
  desc: null
  value: 0
backbone:
  desc: null
  value: gpt3
batch_size:
  desc: null
  value: 4
budget:
  desc: null
  value: 1000
checkpoint_freq:
  desc: null
  value: 5
classification_task_ids:
  desc: null
  value:
  - 019
  - '021'
  - '022'
  - '050'
  - 069
  - '137'
  - '139'
  - '195'
config_file:
  desc: null
  value: ''
data_dir:
  desc: null
  value: ./natural-instructions-2.6/tasks/
data_seed:
  desc: null
  value: 42
dataset_config_file:
  desc: null
  value: ''
edits:
  desc: null
  value:
  - del
  - swap
  - sub
  - add
eval_only:
  desc: null
  value: false
key_id:
  desc: null
  value: 0
level:
  desc: null
  value: phrase
load_epoch:
  desc: null
  value: null
meta_dir:
  desc: null
  value: logs/
meta_name:
  desc: null
  value: search.txt
mode:
  desc: null
  value: Instruction Only
model_dir:
  desc: null
  value: ''
model_name:
  desc: null
  value: text-babbage-001
no_train:
  desc: null
  value: false
num_candidates:
  desc: null
  value: 10
num_compose:
  desc: null
  value: 1
num_iter:
  desc: null
  value: 10
num_samples:
  desc: null
  value: 100
num_shots:
  desc: null
  value: 2
num_train:
  desc: null
  value: 100
opts:
  desc: null
  value: []
output_dir:
  desc: null
  value: ''
patience:
  desc: null
  value: 7
print_orig:
  desc: null
  value: false
project_name:
  desc: null
  value: evolutional-prompt
resume:
  desc: null
  value: ''
simulated_anneal:
  desc: null
  value: false
task_idx:
  desc: null
  value: 1
tournament_selection:
  desc: null
  value: 3
train_seed:
  desc: null
  value: 0
transforms:
  desc: null
  value: null
write_preds:
  desc: null
  value: false
