wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.36.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1707130548
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 13
      4: 3.9.12
      5: 0.12.21
      6: 4.36.0
      8:
      - 5
